# Generated by Django 3.0.5 on 2020-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name_plural': 'Room categories'},
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
